import React from 'react';
import ReactDOM from 'react-dom';
import MinimalPairs from './MinimalPairs.js';

const pairs = [
    { name: "beten / Betten", optionOneName: "beten", optionTwoName: "Betten", optionOneAudioUrl: "/audio/german/0beten.ogg", optionTwoAudioUrl: "/audio/german/1Betten.ogg" },
    { name: "fehle / felle", optionOneName: "fehle", optionTwoName: "felle", optionOneAudioUrl: "/audio/german/2fehle.ogg", optionTwoAudioUrl: "/audio/german/3felle.ogg" },
    { name: "Weg / weg", optionOneName: "Weg", optionTwoName: "weg", optionOneAudioUrl: "/audio/german/4Weg.ogg", optionTwoAudioUrl: "/audio/german/5weg.ogg" },
    { name: "stehlt / stellt", optionOneName: "stehlt", optionTwoName: "stellt", optionOneAudioUrl: "/audio/german/6stehlt.ogg", optionTwoAudioUrl: "/audio/german/7stellt.ogg" },
    { name: "gähnt / Gent", optionOneName: "gähnt", optionTwoName: "Gent", optionOneAudioUrl: "/audio/german/10gaehnt.ogg", optionTwoAudioUrl: "/audio/german/11Gent.ogg" },
    { name: "bieten / bitten", optionOneName: "bieten", optionTwoName: "bitten", optionOneAudioUrl: "/audio/german/12bieten.ogg", optionTwoAudioUrl: "/audio/german/13bitten.ogg" },
    { name: "stiehlt / stillt", optionOneName: "stiehlt", optionTwoName: "stillt", optionOneAudioUrl: "/audio/german/18stiehlt.ogg", optionTwoAudioUrl: "/audio/german/19stillt.ogg" },
    { name: "riet / ritt", optionOneName: "riet", optionTwoName: "ritt", optionOneAudioUrl: "/audio/german/20riet.ogg", optionTwoAudioUrl: "/audio/german/21ritt.ogg" },
    { name: "ihn / in", optionOneName: "ihn", optionTwoName: "in", optionOneAudioUrl: "/audio/german/22ihn.ogg", optionTwoAudioUrl: "/audio/german/23in.ogg" },
    { name: "Bahn / Bann", optionOneName: "Bahn", optionTwoName: "Bann", optionOneAudioUrl: "/audio/german/24Bahn.ogg", optionTwoAudioUrl: "/audio/german/25Bann.ogg" },
    { name: "kam / Kamm", optionOneName: "kam", optionTwoName: "Kamm", optionOneAudioUrl: "/audio/german/26kam.ogg", optionTwoAudioUrl: "/audio/german/27Kamm.ogg" },
    { name: "Staat / Stadt", optionOneName: "Staat", optionTwoName: "Stadt", optionOneAudioUrl: "/audio/german/28Staat.ogg", optionTwoAudioUrl: "/audio/german/29Stadt.ogg" },
    { name: "Schlaf / schlaff", optionOneName: "Schlaf", optionTwoName: "schlaff", optionOneAudioUrl: "/audio/german/30Schlaf.ogg", optionTwoAudioUrl: "/audio/german/31schlaff.ogg" },
    { name: "lahm / Lamm", optionOneName: "lahm", optionTwoName: "Lamm", optionOneAudioUrl: "/audio/german/32lahm.ogg", optionTwoAudioUrl: "/audio/german/33Lamm.ogg" },
    { name: "Saat / satt", optionOneName: "Saat", optionTwoName: "satt", optionOneAudioUrl: "/audio/german/34Saat.ogg", optionTwoAudioUrl: "/audio/german/35satt.ogg" },
    { name: "Mus / muss", optionOneName: "Mus", optionTwoName: "muss", optionOneAudioUrl: "/audio/german/40Mus.ogg", optionTwoAudioUrl: "/audio/german/41muss.ogg" },
    { name: "Stuhle / Stulle", optionOneName: "Stuhle", optionTwoName: "Stulle", optionOneAudioUrl: "/audio/german/42Stuhle.ogg", optionTwoAudioUrl: "/audio/german/43Stulle.ogg" },
    { name: "Schote / Schotte", optionOneName: "Schote", optionTwoName: "Schotte", optionOneAudioUrl: "/audio/german/46Schote.ogg", optionTwoAudioUrl: "/audio/german/47Schotte.ogg" },
    { name: "bog / Bock", optionOneName: "bog", optionTwoName: "Bock", optionOneAudioUrl: "/audio/german/48bog.ogg", optionTwoAudioUrl: "/audio/german/49Bock.ogg" },
    { name: "Tone / Tonne", optionOneName: "Tone", optionTwoName: "Tonne", optionOneAudioUrl: "/audio/german/50Tone.ogg", optionTwoAudioUrl: "/audio/german/51Tonne.ogg" },
    { name: "Ofen / offen", optionOneName: "Ofen", optionTwoName: "offen", optionOneAudioUrl: "/audio/german/52Ofen.ogg", optionTwoAudioUrl: "/audio/german/53offen.ogg" },
    { name: "Hefe / Höfe", optionOneName: "Hefe", optionTwoName: "Höfe", optionOneAudioUrl: "/audio/german/56Hefe.ogg", optionTwoAudioUrl: "/audio/german/57Hoefe.ogg" },
    { name: "Lehne / Löhne", optionOneName: "Lehne", optionTwoName: "Löhne", optionOneAudioUrl: "/audio/german/58Lehne.ogg", optionTwoAudioUrl: "/audio/german/59Loehne.ogg" },
    { name: "Sehne / Söhne", optionOneName: "Sehne", optionTwoName: "Söhne", optionOneAudioUrl: "/audio/german/60Sehne.ogg", optionTwoAudioUrl: "/audio/german/61Soehne.ogg" },
    { name: "schon / schön", optionOneName: "schon", optionTwoName: "schön", optionOneAudioUrl: "/audio/german/62schon.ogg", optionTwoAudioUrl: "/audio/german/63schoen.ogg" },
    { name: "losen / lösen", optionOneName: "losen", optionTwoName: "lösen", optionOneAudioUrl: "/audio/german/64losen.ogg", optionTwoAudioUrl: "/audio/german/65loesen.ogg" },
    { name: "Bogen / Bögen", optionOneName: "Bogen", optionTwoName: "Bögen", optionOneAudioUrl: "/audio/german/66Bogen.ogg", optionTwoAudioUrl: "/audio/german/67Boegen.ogg" },
    { name: "Gent / gönnt", optionOneName: "Gent", optionTwoName: "gönnt", optionOneAudioUrl: "/audio/german/68Gent.ogg", optionTwoAudioUrl: "/audio/german/69goennt.ogg" },
    { name: "helle / Hölle", optionOneName: "helle", optionTwoName: "Hölle", optionOneAudioUrl: "/audio/german/70helle.ogg", optionTwoAudioUrl: "/audio/german/71Hoelle.ogg" },
    { name: "kennen / können", optionOneName: "kennen", optionTwoName: "können", optionOneAudioUrl: "/audio/german/72kennen.ogg", optionTwoAudioUrl: "/audio/german/73koennen.ogg" },
    { name: "konnte / könnte", optionOneName: "konnte", optionTwoName: "könnte", optionOneAudioUrl: "/audio/german/74konnte.ogg", optionTwoAudioUrl: "/audio/german/75koennte.ogg" },
    { name: "Biene / Bühne", optionOneName: "Biene", optionTwoName: "Bühne", optionOneAudioUrl: "/audio/german/84Biene.ogg", optionTwoAudioUrl: "/audio/german/85Buehne.ogg" },
    { name: "Kiel / kühl", optionOneName: "Kiel", optionTwoName: "kühl", optionOneAudioUrl: "/audio/german/86Kiel.ogg", optionTwoAudioUrl: "/audio/german/87kuehl.ogg" },
    { name: "liegen / lügen", optionOneName: "liegen", optionTwoName: "lügen", optionOneAudioUrl: "/audio/german/88liegen.ogg", optionTwoAudioUrl: "/audio/german/89luegen.ogg" },
    { name: "Liste / Lüste", optionOneName: "Liste", optionTwoName: "Lüste", optionOneAudioUrl: "/audio/german/96Liste.ogg", optionTwoAudioUrl: "/audio/german/97Lueste.ogg" },
    { name: "Kiste / Küste", optionOneName: "Kiste", optionTwoName: "Küste", optionOneAudioUrl: "/audio/german/98Kiste.ogg", optionTwoAudioUrl: "/audio/german/99Kueste.ogg" },
    { name: "Lifte / Lüfte", optionOneName: "Lifte", optionTwoName: "Lüfte", optionOneAudioUrl: "/audio/german/100Lifte.ogg", optionTwoAudioUrl: "/audio/german/101Luefte.ogg" },
    { name: "Mutter / Mütter", optionOneName: "Mutter", optionTwoName: "Mütter", optionOneAudioUrl: "/audio/german/104Mutter.ogg", optionTwoAudioUrl: "/audio/german/105Muetter.ogg" },
    { name: "essen / äsen", optionOneName: "essen", optionTwoName: "äsen", optionOneAudioUrl: "/audio/german/108essen.ogg", optionTwoAudioUrl: "/audio/german/109aesen.ogg" },
    { name: "meine / Miene", optionOneName: "meine", optionTwoName: "Miene", optionOneAudioUrl: "/audio/german/112meine.ogg", optionTwoAudioUrl: "/audio/german/113Miene.ogg" },
    { name: "Beine / Biene", optionOneName: "Beine", optionTwoName: "Biene", optionOneAudioUrl: "/audio/german/114Beine.ogg", optionTwoAudioUrl: "/audio/german/115Biene.ogg" },
    { name: "Leibe / Liebe", optionOneName: "Leibe", optionTwoName: "Liebe", optionOneAudioUrl: "/audio/german/120Leibe.ogg", optionTwoAudioUrl: "/audio/german/121Liebe.ogg" },
    { name: "Haufen / häufen", optionOneName: "Haufen", optionTwoName: "häufen", optionOneAudioUrl: "/audio/german/128Haufen.ogg", optionTwoAudioUrl: "/audio/german/129haeufen.ogg" },
    { name: "Laute / Leute", optionOneName: "Laute", optionTwoName: "Leute", optionOneAudioUrl: "/audio/german/130Laute.ogg", optionTwoAudioUrl: "/audio/german/131Leute.ogg" },
    { name: "Säule / Seile", optionOneName: "Säule", optionTwoName: "Seile", optionOneAudioUrl: "/audio/german/136Saeule.ogg", optionTwoAudioUrl: "/audio/german/137Seile.ogg" },
    { name: "Eule / Eile", optionOneName: "Eule", optionTwoName: "Eile", optionOneAudioUrl: "/audio/german/138Eule.ogg", optionTwoAudioUrl: "/audio/german/139Eile.ogg" },
    { name: "Leute / leite", optionOneName: "Leute", optionTwoName: "leite", optionOneAudioUrl: "/audio/german/140Leute.ogg", optionTwoAudioUrl: "/audio/german/141leite.ogg" },
    { name: "hindern / hintern", optionOneName: "hindern", optionTwoName: "hintern", optionOneAudioUrl: "/audio/german/160hindern.ogg", optionTwoAudioUrl: "/audio/german/161hintern.ogg" },
    { name: "Sonde / sonnte", optionOneName: "Sonde", optionTwoName: "sonnte", optionOneAudioUrl: "/audio/german/162Sonde.ogg", optionTwoAudioUrl: "/audio/german/163sonnte.ogg" },
    { name: "Seide / Seite", optionOneName: "Seide", optionTwoName: "Seite", optionOneAudioUrl: "/audio/german/164Seide.ogg", optionTwoAudioUrl: "/audio/german/165Seite.ogg" },
    { name: "verging / wer ging", optionOneName: "verging", optionTwoName: "wer ging", optionOneAudioUrl: "/audio/german/172verging.ogg", optionTwoAudioUrl: "/audio/german/173werging.ogg" },
    { name: "krieche / krache", optionOneName: "krieche", optionTwoName: "krache", optionOneAudioUrl: "/audio/german/174krieche.ogg", optionTwoAudioUrl: "/audio/german/175krache.ogg" },
    { name: "sprich / sprach", optionOneName: "sprich", optionTwoName: "sprach", optionOneAudioUrl: "/audio/german/180sprich.ogg", optionTwoAudioUrl: "/audio/german/181sprach.ogg" },
    { name: "reisen / reißen", optionOneName: "reisen", optionTwoName: "reißen", optionOneAudioUrl: "/audio/german/186reisen.ogg", optionTwoAudioUrl: "/audio/german/187reissen.ogg" },
    { name: "weisen / weißen", optionOneName: "weisen", optionTwoName: "weißen", optionOneAudioUrl: "/audio/german/192weisen.ogg", optionTwoAudioUrl: "/audio/german/193weissen.ogg" },
    { name: "Zoo / so", optionOneName: "Zoo", optionTwoName: "so", optionOneAudioUrl: "/audio/german/196Zoo.ogg", optionTwoAudioUrl: "/audio/german/197so.ogg" },
    { name: "Zeile / Seile", optionOneName: "Zeile", optionTwoName: "Seile", optionOneAudioUrl: "/audio/german/200Zeile.ogg", optionTwoAudioUrl: "/audio/german/201Seile.ogg" },
    { name: "zog / sog", optionOneName: "zog", optionTwoName: "sog", optionOneAudioUrl: "/audio/german/202zog.ogg", optionTwoAudioUrl: "/audio/german/203sog.ogg" },
    { name: "Schulz / Schurz", optionOneName: "Schulz", optionTwoName: "Schurz", optionOneAudioUrl: "/audio/german/212Schulz.ogg", optionTwoAudioUrl: "/audio/german/213Schurz.ogg" },
    { name: "wollte / Worte", optionOneName: "wollte", optionTwoName: "Worte", optionOneAudioUrl: "/audio/german/214wollte.ogg", optionTwoAudioUrl: "/audio/german/215Worte.ogg" },
    { name: "built / Bild", optionOneName: "built", optionTwoName: "Bild", optionOneAudioUrl: "/audio/german/216built.ogg", optionTwoAudioUrl: "/audio/german/217Bild.ogg" },
    { name: "feel / viel", optionOneName: "feel", optionTwoName: "viel", optionOneAudioUrl: "/audio/german/218feel.ogg", optionTwoAudioUrl: "/audio/german/219viel.ogg" },
    { name: "Oper / Ober", optionOneName: "Oper", optionTwoName: "Ober", optionOneAudioUrl: "/audio/german/228Oper.ogg", optionTwoAudioUrl: "/audio/german/229Ober.ogg" },
    { name: "Paar / Bar", optionOneName: "Paar", optionTwoName: "Bar", optionOneAudioUrl: "/audio/german/230Paar.ogg", optionTwoAudioUrl: "/audio/german/231Bar.ogg" },
    { name: "tanken / danken", optionOneName: "tanken", optionTwoName: "danken", optionOneAudioUrl: "/audio/german/232tanken.ogg", optionTwoAudioUrl: "/audio/german/233danken.ogg" },
    { name: "Tier / dir", optionOneName: "Tier", optionTwoName: "dir", optionOneAudioUrl: "/audio/german/234Tier.ogg", optionTwoAudioUrl: "/audio/german/235dir.ogg" },
    { name: "Kunst / Gunst", optionOneName: "Kunst", optionTwoName: "Gunst", optionOneAudioUrl: "/audio/german/238Kunst.ogg", optionTwoAudioUrl: "/audio/german/239Gunst.ogg" },
    { name: "Ecke / Egge", optionOneName: "Ecke", optionTwoName: "Egge", optionOneAudioUrl: "/audio/german/240Ecke.ogg", optionTwoAudioUrl: "/audio/german/241Egge.ogg" },
    { name: "im Haus / im Aus", optionOneName: "im Haus", optionTwoName: "im Aus", optionOneAudioUrl: "/audio/german/242imHaus.ogg", optionTwoAudioUrl: "/audio/german/243imAus.ogg" },
    { name: "aus Hessen / aus Essen", optionOneName: "aus Hessen", optionTwoName: "aus Essen", optionOneAudioUrl: "/audio/german/244ausHessen.ogg", optionTwoAudioUrl: "/audio/german/245ausEssen.ogg" },
    { name: "wie hier / wie ihr", optionOneName: "wie hier", optionTwoName: "wie ihr", optionOneAudioUrl: "/audio/german/246wiehier.ogg", optionTwoAudioUrl: "/audio/german/247wieihr.ogg" },
    { name: "vier / wir", optionOneName: "vier", optionTwoName: "wir", optionOneAudioUrl: "/audio/german/249vier.ogg", optionTwoAudioUrl: "/audio/german/250wir.ogg" },
    { name: "fangen / Wangen", optionOneName: "fangen", optionTwoName: "Wangen", optionOneAudioUrl: "/audio/german/251fangen.ogg", optionTwoAudioUrl: "/audio/german/252Wangen.ogg" },
    { name: "Wicht / wischt", optionOneName: "Wicht", optionTwoName: "wischt", optionOneAudioUrl: "/audio/german/253Wicht.ogg", optionTwoAudioUrl: "/audio/german/254wischt.ogg" },
    { name: "Kirsche / Kirche", optionOneName: "Kirsche", optionTwoName: "Kirche", optionOneAudioUrl: "/audio/german/255Kirsche.ogg", optionTwoAudioUrl: "/audio/german/256Kirche.ogg" },
    { name: "Menschen / Männchen", optionOneName: "Menschen", optionTwoName: "Männchen", optionOneAudioUrl: "/audio/german/257Menschen.ogg", optionTwoAudioUrl: "/audio/german/258Maennchen.ogg" },
    { name: "zähmen / Zähnen", optionOneName: "zähmen", optionTwoName: "Zähnen", optionOneAudioUrl: "/audio/german/261zaehmen.ogg", optionTwoAudioUrl: "/audio/german/262Zaehnen.ogg" },
    { name: "am / an", optionOneName: "am", optionTwoName: "an", optionOneAudioUrl: "/audio/german/263am.ogg", optionTwoAudioUrl: "/audio/german/264an.ogg" },
    { name: "dünner / Dünger", optionOneName: "dünner", optionTwoName: "Dünger", optionOneAudioUrl: "/audio/german/265duenner.ogg", optionTwoAudioUrl: "/audio/german/266Duenger.ogg" },
    { name: "ran / Rang", optionOneName: "ran", optionTwoName: "Rang", optionOneAudioUrl: "/audio/german/267ran.ogg", optionTwoAudioUrl: "/audio/german/268Rang.ogg" },
    { name: "Land / langt", optionOneName: "Land", optionTwoName: "langt", optionOneAudioUrl: "/audio/german/269Land.ogg", optionTwoAudioUrl: "/audio/german/270langt.ogg" },
    { name: "dümmer / Dünger", optionOneName: "dümmer", optionTwoName: "Dünger", optionOneAudioUrl: "/audio/german/271duemmer.ogg", optionTwoAudioUrl: "/audio/german/272Duenger.ogg" },
    { name: "Lamm / lang", optionOneName: "Lamm", optionTwoName: "lang", optionOneAudioUrl: "/audio/german/273Lamm.ogg", optionTwoAudioUrl: "/audio/german/274lang.ogg" },
    { name: "Miete / Mitte", optionOneName: "Miete", optionTwoName: "Mitte", optionOneAudioUrl: "/audio/german/277Miete.ogg", optionTwoAudioUrl: "/audio/german/278Mitte.ogg" },
    { name: "Stiel / still", optionOneName: "Stiel", optionTwoName: "still", optionOneAudioUrl: "/audio/german/279Stiel.ogg", optionTwoAudioUrl: "/audio/german/280still.ogg" },
    { name: "bieten / bitten", optionOneName: "bieten", optionTwoName: "bitten", optionOneAudioUrl: "/audio/german/281bieten.ogg", optionTwoAudioUrl: "/audio/german/282bitten.ogg" },
    { name: "Seele / Säle", optionOneName: "Seele", optionTwoName: "Säle", optionOneAudioUrl: "/audio/german/283Seele.ogg", optionTwoAudioUrl: "/audio/german/284Saele.ogg" },
    { name: "bete / bäte", optionOneName: "bete", optionTwoName: "bäte", optionOneAudioUrl: "/audio/german/285bete.ogg", optionTwoAudioUrl: "/audio/german/286baete.ogg" },
    { name: "Genen / gähnen", optionOneName: "Genen", optionTwoName: "gähnen", optionOneAudioUrl: "/audio/german/287Genen.ogg", optionTwoAudioUrl: "/audio/german/288gaehnen.ogg" },
    { name: "stehlen / stellen", optionOneName: "stehlen", optionTwoName: "stellen", optionOneAudioUrl: "/audio/german/289stehlen.ogg", optionTwoAudioUrl: "/audio/german/290stellen.ogg" },
    { name: "fehlen / fällen", optionOneName: "fehlen", optionTwoName: "fällen", optionOneAudioUrl: "/audio/german/291fehlen.ogg", optionTwoAudioUrl: "/audio/german/292faellen.ogg" },
    { name: "wann / Wahn", optionOneName: "wann", optionTwoName: "Wahn", optionOneAudioUrl: "/audio/german/293wann.ogg", optionTwoAudioUrl: "/audio/german/294Wahn.ogg" },
    { name: "Lamm / lahm", optionOneName: "Lamm", optionTwoName: "lahm", optionOneAudioUrl: "/audio/german/295Lamm.ogg", optionTwoAudioUrl: "/audio/german/296lahm.ogg" },
    { name: "Stall / Stahl", optionOneName: "Stall", optionTwoName: "Stahl", optionOneAudioUrl: "/audio/german/297Stall.ogg", optionTwoAudioUrl: "/audio/german/298Stahl.ogg" },
    { name: "Quellen / quälen", optionOneName: "Quellen", optionTwoName: "quälen", optionOneAudioUrl: "/audio/german/299Quellen.ogg", optionTwoAudioUrl: "/audio/german/300quaelen.ogg" },
    { name: "Teller / Täler", optionOneName: "Teller", optionTwoName: "Täler", optionOneAudioUrl: "/audio/german/301Teller.ogg", optionTwoAudioUrl: "/audio/german/302Taeler.ogg" },
    { name: "gute / Güte", optionOneName: "gute", optionTwoName: "Güte", optionOneAudioUrl: "/audio/german/303gute.ogg", optionTwoAudioUrl: "/audio/german/304Guete.ogg" },
    { name: "Tier / Tür", optionOneName: "Tier", optionTwoName: "Tür", optionOneAudioUrl: "/audio/german/305Tier.ogg", optionTwoAudioUrl: "/audio/german/306Tuer.ogg" },
    { name: "liegen / lügen", optionOneName: "liegen", optionTwoName: "lügen", optionOneAudioUrl: "/audio/german/307liegen.ogg", optionTwoAudioUrl: "/audio/german/308luegen.ogg" },
    { name: "sieden / Süden", optionOneName: "sieden", optionTwoName: "Süden", optionOneAudioUrl: "/audio/german/309sieden.ogg", optionTwoAudioUrl: "/audio/german/310Sueden.ogg" },
    { name: "lösen / losen", optionOneName: "lösen", optionTwoName: "losen", optionOneAudioUrl: "/audio/german/65loesen.ogg", optionTwoAudioUrl: "/audio/german/64losen.ogg" },
    { name: "Böden / Boden", optionOneName: "Böden", optionTwoName: "Boden", optionOneAudioUrl: "/audio/german/315Boeden.ogg", optionTwoAudioUrl: "/audio/german/316Boden.ogg" },
    { name: "ticken / Tücken", optionOneName: "ticken", optionTwoName: "Tücken", optionOneAudioUrl: "/audio/german/317ticken.ogg", optionTwoAudioUrl: "/audio/german/318Tuecken.ogg" },
    { name: "sticken / Stücken", optionOneName: "sticken", optionTwoName: "Stücken", optionOneAudioUrl: "/audio/german/319sticken.ogg", optionTwoAudioUrl: "/audio/german/320Stuecken.ogg" },
    { name: "Kiste / Küste", optionOneName: "Kiste", optionTwoName: "Küste", optionOneAudioUrl: "/audio/german/321Kiste.ogg", optionTwoAudioUrl: "/audio/german/322Kueste.ogg" },
    { name: "Stück / Stuck", optionOneName: "Stück", optionTwoName: "Stuck", optionOneAudioUrl: "/audio/german/323Stueck.ogg", optionTwoAudioUrl: "/audio/german/324Stuck.ogg" },
    { name: "zücken / zucken", optionOneName: "zücken", optionTwoName: "zucken", optionOneAudioUrl: "/audio/german/325zuecken.ogg", optionTwoAudioUrl: "/audio/german/326zucken.ogg" },
    { name: "Mücken / mucken", optionOneName: "Mücken", optionTwoName: "mucken", optionOneAudioUrl: "/audio/german/327Muecken.ogg", optionTwoAudioUrl: "/audio/german/328mucken.ogg" },
    { name: "Liebe / lieber", optionOneName: "Liebe", optionTwoName: "lieber", optionOneAudioUrl: "/audio/german/121Liebe.ogg", optionTwoAudioUrl: "/audio/german/332lieber.ogg" },
    { name: "Bässe / besser", optionOneName: "Bässe", optionTwoName: "besser", optionOneAudioUrl: "/audio/german/333Baesse.ogg", optionTwoAudioUrl: "/audio/german/334besser.ogg" },
    { name: "Polen / Pollen", optionOneName: "Polen", optionTwoName: "Pollen", optionOneAudioUrl: "/audio/german/335Polen.ogg", optionTwoAudioUrl: "/audio/german/336Pollen.ogg" },
    { name: "Schrot / Schrott", optionOneName: "Schrot", optionTwoName: "Schrott", optionOneAudioUrl: "/audio/german/337Schrot.ogg", optionTwoAudioUrl: "/audio/german/338Schrott.ogg" },
    { name: "er sucht / die Sucht", optionOneName: "er sucht", optionTwoName: "die Sucht", optionOneAudioUrl: "/audio/german/339ersucht.ogg", optionTwoAudioUrl: "/audio/german/340dieSucht.ogg" },
    { name: "er bucht / die Bucht", optionOneName: "er bucht", optionTwoName: "die Bucht", optionOneAudioUrl: "/audio/german/341erbucht.ogg", optionTwoAudioUrl: "/audio/german/342dieBucht.ogg" },
    { name: "Buße / Busse", optionOneName: "Buße", optionTwoName: "Busse", optionOneAudioUrl: "/audio/german/343Busse.ogg", optionTwoAudioUrl: "/audio/german/344Busse.ogg" },
    { name: "bute / bote", optionOneName: "bute", optionTwoName: "bote", optionOneAudioUrl: "/audio/german/345bute.ogg", optionTwoAudioUrl: "/audio/german/346bote.ogg" },
    { name: "biete / bete", optionOneName: "biete", optionTwoName: "bete", optionOneAudioUrl: "/audio/german/347biete.ogg", optionTwoAudioUrl: "/audio/german/348bete.ogg" },
    { name: "ströck / strück", optionOneName: "ströck", optionTwoName: "strück", optionOneAudioUrl: "/audio/german/349stroeck.ogg", optionTwoAudioUrl: "/audio/german/350strueck.ogg" },
    { name: "strick / ströck", optionOneName: "strick", optionTwoName: "ströck", optionOneAudioUrl: "/audio/german/351strick.ogg", optionTwoAudioUrl: "/audio/german/352stroeck.ogg" },
    { name: "strack / strock", optionOneName: "strack", optionTwoName: "strock", optionOneAudioUrl: "/audio/german/353strack.ogg", optionTwoAudioUrl: "/audio/german/354strock.ogg" },
    { name: "strock / struck", optionOneName: "strock", optionTwoName: "struck", optionOneAudioUrl: "/audio/german/355strock.ogg", optionTwoAudioUrl: "/audio/german/356struck.ogg" },
    { name: "strack / ströck", optionOneName: "strack", optionTwoName: "ströck", optionOneAudioUrl: "/audio/german/357strack.ogg", optionTwoAudioUrl: "/audio/german/358stroeck.ogg" },
    { name: "strack / streck", optionOneName: "strack", optionTwoName: "streck", optionOneAudioUrl: "/audio/german/359strack.ogg", optionTwoAudioUrl: "/audio/german/360streck.ogg" },
    { name: "bute / böte", optionOneName: "bute", optionTwoName: "böte", optionOneAudioUrl: "/audio/german/361bute.ogg", optionTwoAudioUrl: "/audio/german/362boete.ogg" },
    { name: "bute / büte", optionOneName: "bute", optionTwoName: "büte", optionOneAudioUrl: "/audio/german/363bute.ogg", optionTwoAudioUrl: "/audio/german/364buete.ogg" },
];

ReactDOM.render(
    <MinimalPairs pairs={pairs}/>,
    document.getElementById('root')
);
